sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint:
    access-key-id:

    bucket-name: sky-takeout-beimeng

  redis:
    host: localhost
    port: 6379
    password:
    database: 1
  wechat:
    appid:

