sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJEy1GKg7DuhdWW4Xw9
    access-key-secret: xpbpZ38ZVJ0JbdATMROFsze6gmquMR
    bucket-name: sky-takeout-beimeng

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wxb4ff5a9db00dc0e0
    secret: d47a62e8943709f18fb1805c79a96438
